# Site settings
title: MitchBox
header-img: img/home-bg.jpg
email: 
description: "Dev Notes"
baseurl: ""
url: "http://mitchbox.github.io/mitch-test"
twitter_username: 
github_username:  mitchbox
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
